spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://34.228.27.228:3306/pjt_happy?characterEncoding=UTF-8
    username: root
    password: Password1!

mybatis:
  mapper-locations: com/happy/**/mapper/*.xml

server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true