spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.234.93.196:3306/pjt_happy?characterEncoding=UTF-8
    username: root
    password: Password1!

mybatis:
  mapper-locations: com/happy/**/mapper/*.xml

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true